name: Hello World Action $MY_NAME
on: [push]

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - users: ./action-a
      env:
        MY_NAME: "Action!!"